# https://github.com/robvanderleek/create-issue-branch
mode: chatops
autoCloseIssue: true
branchName: '${issue.user.login}/${issue.number}-${issue.title}'
silent: false
branches:
  - label: question
    skip: true
  - label: '*'
    name: dev
