#################################
## Hugo settings               ##
#################################

baseurl = "/"
languageCode = "en-us"
title = "Ajay's blog"
theme = "beautifulhugo"
enableEmoji = true
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
copyright = "&copy; 2020 Ajay Mehta"
enableGitInfo = true
math = true

[privacy]
    [privacy.disqus]
        disable = true
    [privacy.googleAnalytics]
        disable = true
    [privacy.instagram]
        disable = true
    [privacy.twitter]
        disable = true
    [privacy.vimeo]
        disable = true
    [privacy.youtube]
        disable = true


[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

#################################
## Theme-specific settings     ##
#################################

#################
# beautifulhugo #
#################

[params]
    homeTitle = "" # Set a different text for the header on the home page
    description = "Personal website of Ajay Mehta."
    useHLJS = false
    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    logo = "img/dolphins_20140914.jpg"
    # path to the favicon, under "static"
    favicon = "img/favicon.ico"
    dateFormat = "January 2, 2006"
    commit = "https://github.com/ajaykmehta/blog/tree/"
    rss = true
    comments = false
    readingTime = true
    wordCount = false
    socialShare = false
    showRelatedPosts = true
    hideAuthor = false

[Author]
    name = "Ajay Mehta"
    # website = "https://ajaymehta.netlify.com"
    github = "ajaykmehta"
    gitlab = "ajaymehta1"
    linkedin = "ajay-mehta-b781ba1"
    # stackoverflow = ""