#################################
## Hugo settings               ##
#################################

baseurl = "https://ajaymehta.netlify.com/"
languageCode = "en-us"
title = "Ajay's blog"
theme = "beautifulhugo"
enableEmoji = true
googleAnalytics = ""
disqusShortname = ""
# https://ropensci.org/technotes/2020/04/23/rmd-learnings
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "index\\.html"]
enableGitInfo = true
# https://gohugo.io/templates/shortcode-templates/#inline-shortcodes
enableInlineShortcodes = true
math = true
footnoteReturnLinkContents = "↩"
metaDataFormat = "yaml"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      # Render inline HTML + JS
      unsafe = true
      xhtml = false
  [markup.highlight]
    # https://xyproto.github.io/splash/docs/longer/index.html
    style = "dracula"
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[privacy]
    [privacy.disqus]
        disable = true
    [privacy.googleAnalytics]
        disable = true
        respectDoNotTrack = true
        useSessionStorage = true
    [privacy.instagram]
        disable = true
    [privacy.twitter]
        disable = false
        enableDNT = true
        simple = false
    [privacy.vimeo]
        disable = false
        simple = false
    [privacy.youtube]
        disable = false
        privacyEnhanced = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[menu]

[[menu.main]]
    identifier = "about"
    name = "About"
    pre = "<i class='far fa-address-card'></i>"
    url = "about/"
    weight = -100

[[menu.main]]
    name = "Categories"
    pre = "<i class='fas fa-star'></i>"
    url = "categories"
    weight = 3

[[menu.main]]
    name = "Tags"
    pre = "<i class='fas fa-sticky-note'></i>"
    url = "tags"
    weight = 3


#################################
## Theme-specific settings     ##
#################################

#################
# beautifulhugo #
#################

[params]
    homeTitle = "" # Set a different text for the header on the home page
    description = "Personal website of Ajay Mehta."
    useHLJS = false
    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    logo = "img/dolphins_20140914.png"
    # path to the favicon, under "static"
    favicon = "img/favicon.ico"
    dateFormat = "January 2, 2006"
    commit = "https://github.com/ajaykmehta/blog/tree/"
    rss = true
    comments = true
    readingTime = true
    wordCount = false
    socialShare = true
    showRelatedPosts = true
    hideAuthor = true
    # These settings are for utterances. Affect customized single page template.
    repo = "ajaykmehta/blog"
    # dark-blue,github-dark-orange,github-dark,github-light,icy-dark,photon-dark
    commentsTheme = "github-light"

[Author]
    name = "Ajay Mehta"
    # website = "https://ajaymehta.netlify.com"
    github = "ajaykmehta"
    gitlab = "ajaymehta1"
    linkedin = "ajay-mehta-b781ba1"
    # stackoverflow = ""