
baseurl = "/"
languageCode = "en-us"
title = "A Hugo website"
theme = "hugo-lithium"
enableEmoji = true
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
copyright = "&copy; 2017 Ajay Mehta"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/ajaykmehta"
    weight = 2

[params]
    description = "Personal website of Ajay Mehta."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml", "tex", "haskell", "xml", "sql", "stan", "python", "powershell", "go", "excel", "cs", "css", "cpp"]
    highlightjsTheme = "atelier-dune-dark"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    AuthorName = "Ajay Mehta"
    GitHubUser = "ajaykmehta"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
