baseurl = "/"
languageCode = "en-us"
title = "Ajay's blog"
theme = "beautifulhugo"
enableEmoji = true
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
copyright = "&copy; 2020 Ajay Mehta"
enableGitInfo = true
math = true

[privacy]
    [privacy.disqus]
        disable = true
    [privacy.googleAnalytics]
        disable = true
    [privacy.instagram]
        disable = true
    [privacy.twitter]
        disable = true
    [privacy.vimeo]
        disable = true
    [privacy.youtube]
        disable = true


[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

[params]
    description = "Personal website of Ajay Mehta."
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = [
        "r",
        "yaml",
        "tex",
        "haskell",
        "xml",
        "sql",
        "stan",
        "python",
        "powershell",
        "go",
        "excel",
        "cs",
        "css",
        "cpp"
    ]
    highlightjsTheme = "atelier-dune-dark"
    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    logo = "img/dolphins_20140914.jpg"
    # path to the favicon, under "static"
    favicon = "img/favicon.ico"
    dateFormat = "January 2, 2006"
    AuthorName = "Ajay Mehta"
    GitHubUser = "ajaykmehta"
    commit = "https://github.com/ajaykmehta/blog/tree/"
