# https://alison.rbind.io/post/2019-02-19-hugo-netlify-toml/
[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.73.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.dev]
  command = "hugo -D -b https://dev--ajaymehta.netlify.app/"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.73.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.73.0"

# https://drmowinckels.io/blog/2020-05-25-changing-you-blogdown-workflow/
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

