# https://alison.rbind.io/post/2019-02-19-hugo-netlify-toml/
[build]
  publish = "public"
  command = "hugo"
[build.environment]
  HUGO_VERSION = "0.80.0"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.dev]
  command = "hugo -D -F -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo -D -b $DEPLOY_PRIME_URL"

[context.deploy-preview]
  command = "hugo -F -b $DEPLOY_PRIME_URL"

# https://drmowinckels.io/blog/2020-05-25-changing-you-blogdown-workflow/
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
