---
title: "Test post"
author: "Ajay Mehta"
date: '2020-05-03'
description: Template for Rmarkdown
draft: yes
categories: ["R", "testing"]
tags: []
slug: test-rmd
compact-title: no
hljs: true
params:
  theme: ""
output:
  html_page:
    keep_md: false
editor_options:
  markdown:
    doctype: blogdown    
---

This is a R Markdown template for a blog post.

<!-- https://gohugo.io/content-management/summaries/ -->

<!--more-->

```{r setup, include=FALSE}
options(warnPartialMatchArgs = FALSE, warnPartialMatchDollar = FALSE)

if (!("theme" %in% names(params)) || nchar(params$theme) == 0) {
  knitr::opts_chunk$set(
    class.output = "bg-success",
    class.message = "bg-info text-info",
    class.warning = "bg-warning text-warning",
    class.error = "bg-danger text-danger"
  )
}
```

# Section heading in sentence case

Citation of a website[^1].

## Subsection heading

A plot:

```{r my-plot}
plot(1:10)
```

Code chunk:

```{r message=FALSE}
library(tidyverse)
rnorm(10) %>% sum()
```

```{r test, include=FALSE}
a <- 1
a <- 1
a <- 1
a <- 1
a <- 1
a <- 1
a <- 1
```

This is a test: $\overset{f(a)}{a \in \mathbb{R}}$


$$\begin{align}
y_t & = l_{t-1} + \phi{b_{t-1}} + \epsilon_t \\
l_t & = l_{t-1} + \phi{b_{t-1}} + \alpha\epsilon_t \\
b_t & = \phi{b_{t-1}} + \beta\epsilon_t
\end{align}$$

[^1]: Hugo static site generator. https://gohugo.io/
