
# Try merging a pull request when it is approved.
name: merge pull-request
on:
    pull_request_review:
        types:
            - submitted

jobs:
    automerge:
        if: github.event.review.state == 'approved' || !github.event.review
        runs-on: ubuntu-latest
        steps:
            - name: merge pull request
              uses: sudo-bot/action-pull-request-merge@v1.1.1
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  number: ${{ github.event.pull_request.number }}
                  merge-method: squash
